
name: Request For Comment - link
description: Issue koppelen aan Request For Comment
title: "Request For Comment - titel"
labels: ["RFComment"]
projects: ["iStandaarden/11"]
body:
- type: textarea
  id: link
  attributes:
    label: Link naar RFC
    description: "Neem de koppeling naar het RFC hier op"
    value: |
      [Link]()
    render: bash
  validations:
    required: true

